inherit_gem:
  niftany: niftany_rubocop.yml

AllCops:
  TargetRubyVersion: 3.1.2
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'

Rails/ContentTag:
  Exclude:
    - 'app/helpers/blacklight_display_helper.rb'
    - 'app/components/custom_document_component.rb'

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'
    - 'spec/helpers/blacklight_display_helper_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'spec/**/*'
    - 'config/routes.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

RSpec/AnyInstance:
  Exclude:
    - 'spec/helpers/blacklight_display_helper_spec.rb'
    - 'spec/integration/tools_box_spec.rb'

Style/FormatStringToken:
  Exclude:
    - 'config/routes.rb'
