inherit_gem:
  niftany: niftany_rubocop.yml

AllCops:
  TargetRubyVersion: 2.7.5
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'

Rails/ContentTag:
  Exclude:
    - 'app/helpers/blacklight_display_helper.rb'
    - 'app/components/custom_document_component.rb'

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'spec/**/*'

RSpec/AnyInstance:
  Exclude:
    - 'spec/helpers/blacklight_display_helper_spec.rb'
