version: '3.5'
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - ${MYSQL_LOCAL_PORT:-3306}:3306
  solr:
    image: solr:8.11.2-slim
    restart: always
    environment:
      SOLR_STOP_WAIT: 10
      SOLR_USERNAME: ${SOLR_USERNAME}
      SOLR_PASSWORD: ${SOLR_PASSWORD}
    volumes:
    - solr-data:/var/solr
    - type: bind
      source: ./solr
      target: /tmp
    ports:
    - ${SOLR_PORT:-8983}:8983
    command: [
      "/bin/bash",
      "-c",
      "solr -c && solr auth enable -credentials $$SOLR_USERNAME:$$SOLR_PASSWORD -z localhost:9983; solr stop && solr -c -f",]
volumes:
  solr-data:
  mysql-data:
