services:
  mysql:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - ${MYSQL_LOCAL_PORT:-3306}:3306
  solr:
    image: solr:9.10.1-slim
    restart: always
    environment:
      SOLR_STOP_WAIT: 10
      SOLR_USERNAME: ${SOLR_USERNAME}
      SOLR_PASSWORD: ${SOLR_PASSWORD}
      SOLR_HEAP: ${SOLR_HEAP:-512m}
    volumes:
    - solr-data:/var/solr
    - type: bind
      source: ./solr
      target: /opt/solr/server/solr/configsets
    ports:
    - ${SOLR_PORT:-8983}:8983
    command: >
      /bin/bash -c "
        solr -c &
        for i in {1..60}; do
          (echo > /dev/tcp/localhost/9983) >/dev/null 2>&1 && break || sleep 1
        done
        solr auth enable -u $$SOLR_USERNAME:$$SOLR_PASSWORD -z localhost:9983 || true
        solr stop
        solr -c -f
      "
    app:
      build: .
      depends_on:
        - mysql
        - solr
      environment:
        RAILS_ENV: development
        DATABASE_URL: mysql2://root:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
        SOLR_HOST: solr
        SOLR_PORT: 8983
      ports:
        - "3000:3000"
      volumes:
        - .:/app:cached
      command: ["/bin/bash","-lc","bundle exec rails server -b 0.0.0.0 -p 3000"]
volumes:
  solr-data:
  mysql-data:
