load_defaults: 7.25.3
development:
  adapter: solr
  url: "<%= Rails.configuration.solr.query_url %>"

test:
  adapter: solr
  url: "<%= Rails.configuration.solr.query_url %>"

production:
  adapter: solr
  url: "<%= Rails.configuration.solr.query_url %>"